# Apache YAML Features for Git Repositories
# See the documentation at: https://github.com/apache/infrastructure-asfyaml/blob/main/README.md

github:
  description: "Roslyn Code Analysis for Apache Lucene.NET"
  homepage: https://lucenenet.apache.org/
  labels:
    - lucenenet
    - lucene
    - text
    - search
    - information
    - retrieval
    - analysis
    - index
    - query
    - apache
    - hacktoberfest
    - code-analysis

  features:
    # Enable wiki for documentation
    wiki: false
    # Enable issues management
    issues: false
    # Enable projects for project management boards
    projects: false
  rulesets:
    - name: "Default Branch Protection"
      type: branch
      branches:
        includes:
          - "~DEFAULT_BRANCH"
          - "release/*"
          - "rel/*"
        excludes: []
      bypass_teams:
        - root
      restrict_deletion: true
      restrict_force_push: true
