//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lucene.Net.CodeAnalysis.Dev {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Lucene.Net.CodeAnalysis.Dev.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string LuceneDev1000_AnalyzerDescription {
            get {
                return ResourceManager.GetString("LuceneDev1000_AnalyzerDescription", resourceCulture);
            }
        }
        
        internal static string LuceneDev1000_AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("LuceneDev1000_AnalyzerMessageFormat", resourceCulture);
            }
        }
        
        internal static string LuceneDev1000_AnalyzerTitle {
            get {
                return ResourceManager.GetString("LuceneDev1000_AnalyzerTitle", resourceCulture);
            }
        }
        
        internal static string LuceneDev1001_AnalyzerDescription {
            get {
                return ResourceManager.GetString("LuceneDev1001_AnalyzerDescription", resourceCulture);
            }
        }
        
        internal static string LuceneDev1001_AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("LuceneDev1001_AnalyzerMessageFormat", resourceCulture);
            }
        }
        
        internal static string LuceneDev1001_AnalyzerTitle {
            get {
                return ResourceManager.GetString("LuceneDev1001_AnalyzerTitle", resourceCulture);
            }
        }
        
        internal static string LuceneDev1002_AnalyzerDescription {
            get {
                return ResourceManager.GetString("LuceneDev1002_AnalyzerDescription", resourceCulture);
            }
        }
        
        internal static string LuceneDev1002_AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("LuceneDev1002_AnalyzerMessageFormat", resourceCulture);
            }
        }
        
        internal static string LuceneDev1002_AnalyzerTitle {
            get {
                return ResourceManager.GetString("LuceneDev1002_AnalyzerTitle", resourceCulture);
            }
        }
        
        internal static string LuceneDev1003_AnalyzerDescription {
            get {
                return ResourceManager.GetString("LuceneDev1003_AnalyzerDescription", resourceCulture);
            }
        }
        
        internal static string LuceneDev1003_AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("LuceneDev1003_AnalyzerMessageFormat", resourceCulture);
            }
        }
        
        internal static string LuceneDev1003_AnalyzerTitle {
            get {
                return ResourceManager.GetString("LuceneDev1003_AnalyzerTitle", resourceCulture);
            }
        }
        
        internal static string LuceneDev1004_AnalyzerDescription {
            get {
                return ResourceManager.GetString("LuceneDev1004_AnalyzerDescription", resourceCulture);
            }
        }
        
        internal static string LuceneDev1004_AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("LuceneDev1004_AnalyzerMessageFormat", resourceCulture);
            }
        }
        
        internal static string LuceneDev1004_AnalyzerTitle {
            get {
                return ResourceManager.GetString("LuceneDev1004_AnalyzerTitle", resourceCulture);
            }
        }
    }
}
